initContainers:
  - name: velero-plugin-for-aws
    image: ${aws_image}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - all
      runAsNonRoot: true
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  provider: aws
  backupStorageLocation:
    bucket: ${bucket}
    config:
      region: ${region}
  volumeSnapshotLocation:
    config:
      region: ${region}

credentials:
  useSecret: false

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
     drop: ["ALL"]
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 2000
